### ISSUE TITLE
Problem receiving prices for next full night

### ISSUE THREAD

**Issue by jensjakob** [samuelmr/nordpool-node#1]
Hi.

I have problems with hourly prices while using "from" and "to". I would like to receive prices for next night, both before and after midnight. It's ok to do two requests if needed, but I can't understand how the "from" and "to" works for hourly prices.

I thought if I wasn't using any of the "from" or "to" option, the latest prices would been received. But today (before midnight) I was still just receiving the same days prices. Using "from" or "to" field also sometimes just give me one price, not hourly prices, even if using the hourly function. It also seems to be some problem using both "from" and "to" having a "to large range"...

I will try to have a look at the problem, but maybe someone has notice this problem before and have a simple suggestion or solution.

**Comment by samuelmr** [comment]
Thanks for the issue. 

The Nordpool API returns hourly prices for a 24 hour period from 00:00 to 23:00 Norwegian time (CET).

The prices for tomorrow are published usually at 14:42 today. If you try to query prices earlier you may get today's prices.

The from and to parameters just limit the amount of information returned. If Nordpool returns data from Thursday 00 to Thursday 23 and your from corresponds to Thursday 22 CET, you only get one hour of data.

For the same reason, if you ask data from Thursday 22 to Friday 21 (CET), the time range is too wide. You should get a warning and use two requests instead. 

This stuff needs to be documented better.

**Comment by samuelmr** [comment]
BTW, you might be interested in my nordpool-ifttt script, since it's trying to tackle roughly the same problem as your charge-cheap.

**Comment by jensjakob** [comment]
Thanks. Unfortunately I didn't get a notice about your answers.

I've solved it using:
```
	options = {
		area: 'SE3',
		currency: 'EUR',
		to: "2017-07-21 07:00"
	}

	options = {
		area: 'SE3',
		currency: 'EUR',
		to: "2017-07-20 23:00"
	}
```
If I didn't wrote "23:00" for todays prices, I've just receive one price, not per hours.

**Comment by jensjakob** [comment]
This currently (at 23:19) gives me todays prices btw:
```
	options = {
		area: 'SE3',
		currency: 'EUR',
```

**Comment by PetriKarjalainen** [comment]
Having similar issue as @jensjakob. When calling from nordpool-ifttt cron 15:15Z the prices fetched are for the same day not for tomorrow. The console.log(url) on row 85 confirms this. The prices are avail on page 10 anyhow.

**Comment by PetriKarjalainen** [comment]
@samuelmr, you may wanto to fix the typo on row 84 about curency being there several times....

**Comment by samuelmr** [comment]
Tried to tackle this by enhancing the documentation in README. (Include explicit timezone.)

Closing.
