### ISSUE TITLE
Not working with typescript

### ISSUE THREAD

**Issue by martmalo** [samuelmr/nordpool-node#17]
>  Could not find a declaration file for module 'nordpool'. '/Users/.../.../backend/node_modules/nordpool/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/nordpool` if it exists or add a new declaration (.d.ts) file containing `declare module 'nordpool';`https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

Mac M1
Node 16.13.1
Typescript 4.3.4

**Comment by martmalo** [comment]
Update
I just took your code and created my own class and added typing
Closing issue

**Comment by mikaello** [comment]
For others coming here looking for TypeScript typings, here are some:

```typescript
declare module "nordpool" {
  export type PriceOptions = {
    from?: Date | string;
    to?: Date | string;
    area?: string;
    currency?: string;
  };

  interface Prices {
    at(opts?: { date?: Date | string }): Promise<{ date: Date; value: number }>;
    hourly(opts?: PriceOptions): Promise<Array<{ date: Date; value: number }>>;
    daily(opts?: PriceOptions): Promise<Array<{ date: Date; value: number }>>;
    weekly(opts?: PriceOptions): Promise<Array<{ date: Date; value: number }>>;
    monthly(opts?: PriceOptions): Promise<Array<{ date: Date; value: number }>>;
    yearly(opts?: PriceOptions): Promise<Array<{ date: Date; value: number }>>;
    getValues(
      opts?: PriceOptions & {
        area?: string;
      }
    ): Promise<Array<{ date: Date; value: number }>>;
  }

  interface PricesConstructor {
    new (): Prices;
    (): Prices;
    readonly prototype: Prices;
  }

  export const nordpool: { Prices: PricesConstructor };
}
```

I have that in a file `./types/nordpool/index.d.ts`, and have added `./types` to `typeRoots` in my `tsconfig.json`.

**Comment by samuelmr** [comment]
Thanks both @martmalo and @mikaello.

I'm happy to merge pull requests or add co-authors to the project.
