### ISSUE TITLE
Invalid params

### ISSUE THREAD

**Issue by jensjakob** [samuelmr/nordpool-node#2]
Hi. Any idea why I'm keep getting this error?

`{ status: '-2001', message: 'INVALID PARAMS' }`

I've got it before, but just once. Now it's every time I try.

https://github.com/jensjakob/charge-cheap/issues/17

**Comment by samuelmr** [comment]
Based on the `charge-cheap`issue it seems that your json.vehicleInfo is undefined. Have you made sure your JSON is valid and can be parsed?

Very likely unrelated to `nordpool-node`.

**Comment by jensjakob** [comment]
The problem was that my userid became "root" when I ran the script with sudo.
