### ISSUE TITLE
Code in npm module is not the same as when you clone the repo

### ISSUE THREAD

**Issue by lekkimworld** [samuelmr/nordpool-node#6]
I was experiencing an issue parsing the float value that sometimes contained a space. I fixed the issue and wanted to create a PR so I clone the repo and started writing a test for the issue only to figure out the issue was fixed in my fork (removing spaces from the value in prices.js at line 114). Could you republish the module to npm to ensure the npm module contains the fix?

Thx

**Comment by samuelmr** [comment]
Thanks for the heads-up. Version 2.0.1 published to npm.
